# lint runs all linters in this repository
# This workflow is triggered by ci_release.yml workflow
name: lint
on:
  workflow_call:

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rollkit/.github/.github/actions/yamllint@v0.4.1

  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rollkit/.github/.github/actions/markdown-lint@v0.4.1

  dockerfile-lint:
    uses: rollkit/.github/.github/workflows/reuseable_dockerfile_lint.yml@v0.4.1
    with:
      failure-threshold: "error"
